### ISSUE TITLE
No services are working in Sketch Beta 3.2

### ISSUE THREAD

**Issue by tylergaw** [tylergaw/day-player#14]
This doesn't appear to be an issue with any particular service, seems more broad.

Haven't dug into it yet. Only thing I'm seeing in console right now is:
```
Exception: {
    column = 67;
    line = 74;
    sourceURL = "/Users/tyler/Library/Containers/com.bohemiancoding.sketch3.beta/Data/Library/Application Support/com.bohemiancoding.sketch3/Plugins/day-player/Unsplash.it.sketchplugin";
}
```

Will investigate further.

**Comment by davidklaw** [comment]
Pretty certain this has to do with the imageCollection.addImage_name_convertColourspace() call. I'm writing a plugin for 3.2 that's bombing out on the same call.

**Comment by tylergaw** [comment]
Ah cool, thanks for the heads up @davidklaw

**Comment by davidklaw** [comment]
Sure thing. This syntax worked for me.

[imageCollection addImage:img convertColourspace:false]

**Comment by haydenbleasel** [comment]
Hey @tylergaw any ETA on this? I use this plugin on the daily :) Nice work btw.

**Comment by tylergaw** [comment]
@haydenbleasel I think I can get it in tonight (EST). Shouldn't be too bad (famous last words).

**Comment by davidklaw** [comment]
@tylergaw We believe in you! :godmode:

**Comment by davidklaw** [comment]
:100: points

**Comment by tylergaw** [comment]
@davidklaw Thanks for pointing me to that method change. I asked a question about it on the mailing list http://mail.sketchplugins.com/pipermail/dev_sketchplugins.com/2015-January/001094.html to see if we could get some more clarity.

**Comment by tylergaw** [comment]
This is out in master and in a new release https://github.com/tylergaw/day-player/releases/tag/v1.1.0. Gonna close this now. Thanks folks. cc: @haydenbleasel
