### ISSUE TITLE
Images are not being placed

### ISSUE THREAD

**Issue by nolastan** [tylergaw/day-player#21]
I'm unable to get any of the generators to place an image on the artboard or in a group. I've tried on Yosemite and Mavericks with the latest version of Sketch.

**Comment by tylergaw** [comment]
@nolastan This is likely due to changes in the Sketch Plugin format in the latest–3.3 version. I'm taking a look at what is needed to get it updated.

**Comment by tylergaw** [comment]
@nolastan This is fixed in 2.0.0 https://github.com/tylergaw/day-player/releases/tag/v2.0.0
