### ISSUE TITLE
Unresponsive in Sketch 3.3.2?

### ISSUE THREAD

**Issue by finedesign** [tylergaw/day-player#23]
I've installed this plugin as I have other plugins, but when I choose any option (Lorem Pixel, etc.) it does not do anything. This happens if I have a group selected, or nothing at all.

Also, when I tried placekitten, it crashed Sketch.

**Comment by tylergaw** [comment]
@finedesign I'm not having any luck reproducing what you described. I'm using Sketch 3.3.2 and Day Player 2.0 https://github.com/tylergaw/day-player/releases/tag/v2.0.0

Are you using the latest version of Day Player?

**Comment by justiny** [comment]
I can confirm.  Using placekitten crashes Sketch v3.3.3.

**Comment by tylergaw** [comment]
@justiny Bummer. Can you give me a few more details about your setup? OS X version...not sure what else, just anything that might help me reproduce. What about other services? Is it only placekitten that causes Sketch to crash?

**Comment by tylergaw** [comment]
@justiny You may be running into this issue https://github.com/tylergaw/day-player/issues/11

**Comment by tylergaw** [comment]
I'm gonna go ahead and close this out. A lot has changed in the latest 3.0.0 release and I'm not sure this issue is still relevant.
