### ISSUE TITLE
Sketch 3.4.2: day-player creates a 0px x 0px white image 

### ISSUE THREAD

**Issue by jcloutz** [tylergaw/day-player#29]
I recently downloaded this plugin and it seems to have a problem with Sketch 3.4.2. Whenever I try to place an image it creates a 0px by 0px solid white image. Has anyone else had this problem?

**Comment by jbishop228** [comment]
Yeah getting the same issue with the latest Sketch update (3.4.2). A lot of plugins have gone awry since the update it seems.

**Comment by daneclarkcollins** [comment]
Same here.

**Comment by akhalizev** [comment]
For me too.

**Comment by Hiswe** [comment]
Same issue on 3.4.4

**Comment by LukePettway** [comment]
Seems like a lot of plugins are breaking with the new update.

**Comment by OssamaZ** [comment]
The problem is in the "createAndPlaceImg" function, the layer.setRawImage_convertColourspace_collection rises an exception.

**Comment by tylergaw** [comment]
Just got PR #30 merged in to fix this. Will be pushing out a new release shortly.

**Comment by tylergaw** [comment]
@jcloutz Thanks for the report, sorry about the slow response, been a busy couple months. From what I can tell, I have this fixed in the latest release https://github.com/tylergaw/day-player/releases/tag/v2.1.0

**Comment by jcloutz** [comment]
Awesome, thank you @tylergaw.
