### ISSUE TITLE
don't know how to use the Day Player

### ISSUE THREAD

**Issue by yy1105** [tylergaw/day-player#33]
I have sketch 3.83. I used sketch Toolbox and installed Day Player.  I tried select artboard and use Dayplayer to generate image but not able to.  I tired select a group of rectangles, but still not working, please help. 

thanks

**Comment by nareeboy** [comment]
+1

**Comment by spreuss0** [comment]
+1

**Comment by tylergaw** [comment]
Hey folks. This is likely due to Day Player being out of date. I've been away from this project for some time and haven't kept it updated to match changes Sketch as made.

I'm going to pick this back up in #35 to get it working in the latest version of Sketch 40.x

**Comment by tylergaw** [comment]
I'm going to close this out. This is likely cleared up with the 3.0.0 release.
