### ISSUE TITLE
Do you plan to update your plugin for Sketch 40?

### ISSUE THREAD

**Issue by edge0703** [tylergaw/day-player#34]
I want to mention it in The Sketch Handbook (http://www.sketch-handbook.com/), but only if it works with the current version of Sketch.

**Comment by tylergaw** [comment]
hey @edge0703, thanks for the heads up. I've been neglecting this project for a while, but yeah, I should get my shit together and get it updated. I think I can knock it out this weekend. Gonna put in an issue for myself right now.

**Comment by edge0703** [comment]
Good to know, thanks for your effort. I'm especially glad to hear that you will update Day Player, as I mention it along three other plugins in my "Design with real data" chapter.

**Comment by tylergaw** [comment]
Btw; I have this rolling in https://github.com/tylergaw/day-player/pull/36 Hoping to have it out this week. Taking my time with it as I learn a bunch of new stuff Sketch has in the plugins API.
