### ISSUE TITLE
Doesn't work with Sketch 41.2

### ISSUE THREAD

**Issue by edge0703** [tylergaw/day-player#38]
Just installed your plugin in Sketch 41.2, but it doesn't work. Nothing happens when I go to any of the options in Plugins > Day Player. Already restarted Sketch, which didn't help.

**Comment by tylergaw** [comment]
Thanks @edge0703. Are you using macOS Sierra? If so, we have a related discussion in #37

**Comment by edge0703** [comment]
Yes, same issue. Can be closed.
